import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ToastProvider } from "./components/ToastContext";
const inter = Poppins({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Fusion Freights",
  description: "Generated by Fusion Freights",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <ToastProvider>
            <div className="mt-28">{children}</div>
          </ToastProvider>
          <Footer />
        </body>

      </html>

    </>

  );
}
